### ISSUE TITLE
Verifying 3.9999 ISO fails when performed as instructed.

### ISSUE THREAD

**Issue by tinfoil-hacks** [getsolus/help-center-docs#177]
Solus-3.9999-Budgie.sha256sum.sign is not a deteched signature, and in fact includes the sha256sum hash in the file. The specific command that fails is:

```bash
$ gpg --verify Solus-3.9999-Budgie.sha256sum.sign Solus-3.9999-Budgie.sha256sum
gpg: not a detached signature
```

The following solutions work:

Replacing the command above with:

```bash
$ gpg --verify < Solus-3.9999-Budgie.sha256sum.sign
```
and deprecating the use of Solus-3.9999-Budgie.sha256sum.

Or: removing the first 4 lines of Solus-3.9999-Budgie.sha256sum.sign so it does work as a detached signature. Not sure which is best practice, so I didn't want to submit a pull request.

**Comment by JoshStrobl** [comment]
Should now be resolved with updated sign files.
