### ISSUE TITLE
Add steps on how to set up secondary encrypted hard drive

### ISSUE THREAD

**Issue by Johennes** [getsolus/help-center-docs#188]
The current Solus installer (ISO 3.9999) only handles encryption of the primary hard drive (the one which Solus is installed on). However, in nowadays laptops it's not unusual to have two disks, a smaller SSD and a larger HDD. Normally you'd install Solus on the SSD for fast system operation and use the HDD for data storage. As said, the installer will only encrypt the SSD in this case though.

Since disk encryption is a standard feature that (IMHO) everyone should use, I'd like to propose to add a short section underneath the _Disks_ page listing the steps needed for setting up encryption and automatic unlocking during boot for a second hard disk.

**Comment by JoshStrobl** [comment]
We only support FDE, full-disk encryption. So adding documentation for an unsupported configuration is not something I intend on doing.
