### ISSUE TITLE
weird category index pages format 

### ISSUE THREAD

**Issue by Bridouz** [getsolus/help-center-docs#209]
Hi,

When browsing the help center I noticied that index pages for some categories are not well formatted. The ToC is embedded in `<pre><code>` and thus not looking as it should.

Pages concerned are all category indexes (https://getsol.us/articles/package-management/) except for **Packaging**

![Capture du 2019-04-25 15-48-01](https://user-images.githubusercontent.com/10825150/56740790-e3a94f00-6771-11e9-8a36-15c2c735f728.png)

**Comment by JoshStrobl** [comment]
Yea it's fixed now.
