### ISSUE TITLE
Ordering of keys in package.yml

### ISSUE THREAD

**Issue by tomocafe** [getsolus/help-center-docs#241]
Core Team and Global Maintainers are enforcing a strict ordering of keys in package.yml, but it isn't documented in the article on package.yml. Please give clear instructions on the proper ordering of the keys so we can save iterations during the package submission process.

**Comment by JoshStrobl** [comment]
While not a bad idea, I'd much rather this just be done in an automated fashion when Bryan gets around to ypkg3.
