### ISSUE TITLE
Heroes of Newerth doc no longer needed.

### ISSUE THREAD

**Issue by ghost** [getsolus/help-center-docs#244]
The game Heroes of Newerth does not support Linux anymore, so the doc detailing how to install the client is no longer needed.

**Comment by livingsilver94** [comment]
The official Linux support is gone, but it's still being built: https://forums.heroesofnewerth.com/index.php?/topic/31-mac-linux-clients-unofficial-downloads

**Comment by DataDrake** [comment]
I'm going to leave it in for now. If someone reports it as causing an issue, we can update it or nuke it then.
