### ISSUE TITLE
Add docker installation instructions

### ISSUE THREAD

**Issue by raspher** [getsolus/help-center-docs#262]
After docker installation user(s) should be added to docker group.
`sudo usermod -a -G $(whoami)`

But after that, i still cannot run basic docker commands. Is there a way to inform system about changes without doing reboot or restart curernt X session (log out and log in) ?

Can be based on informations from https://docs.docker.com/engine/install/linux-postinstall/

**Comment by minhhut** [comment]
How about `sudo eopkg it docker`?
