### ISSUE TITLE
Add default config file location to nginx help page

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/help-center-docs#285]
# Add the default nginx config file location to the documentation
Page: https://getsol.us/articles/software/nginx/en/

Add a brief note with:
The default location for nginx config files is in `/usr/share/defaults/nginx/`
Copy any needed config files from here to /etc/nginx and modify as needed. 

Use case: Many nginx guides and other nginx users will talk about modifying /etc/nginx/nginx.conf. Unless the user knows they can copy the default file to that location, they may not know what needs to go in it.

**Comment by JoshStrobl** [comment]
You don't need to create an issue associated with a PR.
