### ISSUE TITLE
Hardware Additions

### ISSUE THREAD

**Issue by brucehankins** [getsolus/help-center-docs#287]
Have some hardware to add the the list on help center. Don't know if desktop hardware is included, but I'll add one since the specs and internals are the same as the HP Stream netbooks of old.

HP Pavilion 300-020 - Currently running Budgie but no issues with any other version of Solus

Lenovo IdeaPad S145-15API - Currently running Plasma, but was previously running Budgie and have a Mate VM on the same machine.

**Comment by Staudey** [comment]
Hey there. Going to add that laptop to the list. Unfortunately there isn't a list for desktop devices, but we could add the wireless chipset to the list. Can't find any info on Google though. Could you show me the output of `inxi -N` on the HP Pavillon?
