### ISSUE TITLE
Add link to this github in "Getting Involved"

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/help-center-docs#288]
On the page "Getting Involved" under "Report Bugs" there is only a link to the Developer Portal. There is no indication a user would report a bug anywhere else. This may lead to people filing bugs in Manphest for repos in this project.

Propose:
Add a link to this repo, add a brief note to each link.

```
- [Developer Portal](https://dev.getsol.us)
Most bug reports should be filed here.

- [Solus Github Repos](https://github.com/getsolus)
Certain parts of Solus, such as the Budgie Desktop, have repos on github. Check here to see if the system in question is listed. If so, file the bug in the appropriate repo.
```

I have a branch "report-bugs" with this minor change ready to go if the issue is approved.

**Comment by JoshStrobl** [comment]
You don't need to create an issue associated with a PR.
