### ISSUE TITLE
Structure of `solus-builds` directory

### ISSUE THREAD

**Issue by davidjharder** [getsolus/help-center-docs#397]
We have a mix how we expect the `solus-builds` directory to be structured. If you follow the initial setup, you get something like:

```
~
└── solus-builds
   └── packages    <- monorepo root 
      ├── common
      ├── packages
      └── Taskfile.yml
```

But some parts of the docs expect

```
~
└── solus-builds   <-monorepo root
    ├── common
    ├── packages
    └── Taskfile.yml
```

My preference is the second, for a few reasons:

* Less nested, the majority of contributors will not have other solus repos to organize, so `solus-builds` would only ever contain the monorepo
* I like having the repo "renamed" to solus-builds when it is local, `~/packages` is not descriptive

**Comment by silkeh** [comment]
Agreed on the second. However, I think `~/solus-packages` is probably a better name for the directory.
