### ISSUE TITLE
Document default location of config files for services

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/help-center-docs#400]
Create a document titled something like "Service configuration files" under "Software"
Explain where we keep these files and why.
Note that on other distros, these files are found in /etc (so users who are familiar with that know these are the files they are looking for).

This issue has come up a few times in support questions.
Solus, for statelessness, keeps config files for services such as ssh, pam, ssl etc in 
```
/usr/share/defaults/etc
```

Users coming from other distros, or reading documentation online, may expect these files to be in `etc`. They have asked us where these live in Solus.

The why:
This allows user customization, and can fall back to the defaults we ship in case something happens. It also means that if new defaults are shipped, they don't overwrite the user's custom settings.

To customize a configuration:
Copy to the appropriate directory under /etc. For example: /etc/ssh/ssh_config. Edit the file there.

**Comment by davidjharder** [comment]
See also #305
