### ISSUE TITLE
Add a packaging troubleshooting page

### ISSUE THREAD

**Issue by davidjharder** [getsolus/help-center-docs#411]
We need a page for troubleshooting when packaging.

Things to include:

- How to do a rebase for a conflict
- How to rebase to change commit order (for stacks)
- How to dump a package.yml and solbuild output to GH gist
- Other common issues:
  - ~~History in pspec is crazy -> you forgot to bump~~ Not a thing now: https://github.com/getsolus/packages/commit/0e6cad07d2bf75da639deceada7f5ec4fc2d371c
  - Document the ~~cryptic~~ perfectly reasonable error message from when a tarball signature doesn't match
  - ??

**Comment by davidjharder** [comment]
staudey says: ybump screws up formatting when input string (usually description) is very long

**Comment by davidjharder** [comment]
Reilly's weird tar bug:  http://homebank.free.fr/public/sources/homebank-5.7.1.tar will send a tar.gz, file breaking something

**Comment by malfisya** [comment]
This one is pretty simple, a few packages i encountered stil have `%configure` instead of `%reconfigure`. I just replace it

**Comment by davidjharder** [comment]
Joey says that the use of go-grab means that the first connection to sourceforge fails.

**Comment by davidjharder** [comment]
joey: ./configure $(sed 's|--runstatedir=/run||g' <<< "%CONFOPTS%") if reconfigure doesn't work

**Comment by davidjharder** [comment]
mount: /var/lib/solbuild/roots/unstable-x86_64: WARNING: source write-protected, mounted read-only

**Comment by davidjharder** [comment]
delete cache if solbuild is eating your disk
