### ISSUE TITLE
ISO verificiation on Windows

### ISSUE THREAD

**Issue by EbonJaeger** [getsolus/help-center-docs#420]
Right now, the [Preparing to Install](https://help.getsol.us/docs/user/quick-start/installation/) page only has documentation on how to verify Solus ISOs on Mac and Linux. Assuming there is a way to verify the ISO on Windows, that should be included in that page.

**Comment by davidjharder** [comment]
I've poked at various options. So far I like giving both graphical and command-line method:

* Explaining how to get the checksum with powershell: `Get-FileHash C:\path\to\file.iso` (default is sha256)
* Using 7zip:
  * Open 7zip
  * Navigate to containing folder
  * right-click on iso file
  * Select *CRC* -> *SHA256*

7zip seems like the most reputable utility to point people to that is also reasonably small and portable

**Comment by EbonJaeger** [comment]
With 7zip, it looks like you don't have to open it first:

- Navigate to containing folder
- Right-click on the ISO file
- Select 7-Zip -> CRC -> Sha256

**Comment by Staudey** [comment]
According to [this forum thread](https://discuss.getsol.us/d/9899-verify-iso) (coincidence?) it can also be done in Rufus.

When it comes to the other methods the powershell solution seems elegant enough. Asking people to install 7-zip is a bit much IMO

**Comment by davidjharder** [comment]
> Asking people to install 7-zip is a bit much IMO
Are you saying you wouldn't bother with a graphical method, or just assume they have rufus?

Users will have to download `gpg4win` if they want to verify the signed sha256 file

**Comment by Staudey** [comment]
>  Are you saying you wouldn't bother with a graphical method, or just assume they have rufus?

Well, Rufus is currently the only graphical solution mentioned for preparing a USB install medium, so those users will have Rufus anyway. The DVD method uses Windows built-in tools, so one can't assume anything else is necessarily installed. In that case the Powershell method seems nice to me, as it doesn't require any additional tools to be installed, but of course it has the disadvantage of being a CLI.

It would of course also be possible to simply direct users to install gpg4win and explain how to do the sha256 checks there.

**Comment by davidjharder** [comment]
Once gpg4win is installed the commands are the same as the linux/macos instructions
