### ISSUE TITLE
Update "Sound" article

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/help-center-docs#431]
The Sound article is outdated
https://help.getsol.us/docs/user/software/sound/

It states
"Solus comes with PulseAudio configured by default. It is possible to switch to PipeWire manually using the instructions below."

We have shipped pipewire by default for some time now

**Comment by EbonJaeger** [comment]
Given that the entire article is about installing PipeWire, do we have anything else we can put there? If not, it may make more sense to not have the article at all anymore.
