### ISSUE TITLE
Not work `go-task`

### ISSUE THREAD

**Issue by AlexanderZhirov** [getsolus/help-center-docs#437]
### Summary

![image](https://github.com/getsolus/packages/assets/37277056/42aefe4d-d418-4849-80b5-952cb39dc74c)

If you call the command that is specified in the instructions, then it does not work. And so it is with any data source.

### Steps to reproduce

Execute as in the instructions

### Expected result

Creating a `package.yml` file

### Actual result

`task: No Taskfile found at "/home/user/build/tree"`

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

MATE

### System details

OS: Solus x86_64
Kernel: 6.5.11-263.current

**Comment by davidjharder** [comment]
Going to call this resolved.
