### ISSUE TITLE
Harmonize admontions in style guide

### ISSUE THREAD

**Issue by davidjharder** [getsolus/help-center-docs#495]
The admonitions section of the style guide: https://help.getsol.us/docs/user/contributing/style/#admonitions does not match the admonitions that are actually available to be used from docusaurus: https://docusaurus.io/docs/markdown-features/admonitions 

This happened when we moved from docusaurus 2.x to 3.x

**Comment by malfisya** [comment]
I think I can help with this. Will look at it more tomorrow. Cheers!
