### ISSUE TITLE
Update system requirements and make EFI requirement more discoverable

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/help-center-docs#506]
Improve the information users encounter about system requirements when installing Solus, or troubleshooting installation issues

Update system requirements to have minimum and recommended values. Add the EFI partition minimum size, firmware and display adapter.
To clarify disk space, use GB *and* GiB.
We also need to make the EFI partition minimum value appear in other places it makes sense.

Places to have requirements easily discoverable:
- [Download page](https://getsol.us/download/) - update
- [Installer doc](https://help.getsol.us/docs/user/quick-start/installation/) - add a mention at the start of system requirements and link to the Download page (ideally keep the information in only one place to make sure it stays up to date and consistent)

We also need to make sure the EFI requirement in particular appears wherever appropriate, since it's unique among all OSes and Linux distros.
- Download page: Add in system requirements (see below comment)
- Installer docs: Add a comment to the Multi-boot section that the user will need to ensure the EFI partition is at least 1G.
- Add a comment in [Installation Issues](https://help.getsol.us/docs/user/troubleshooting/installation) troubleshooting

**Comment by TraceyC77** [comment]
Here are my ideas for this. I'll work up code changes after feedback and when I have a bit of time.

On the [Download page](https://getsol.us/download/) we currently have:

```md
 ## System Requirements

    - A blank DVD or a 3GB USB drive.
    - Minimum of 10GB of disk space available.
    - 4GB of RAM for an optimal experience.
    - A 64-bit (x86_64) processor. 
```

Suggestion:

```md
 ## System Requirements

    - A blank DVD or a 3GB USB drive
    - On UEFI systems, an EFI partition of 1GB minimum
    - An internet connection
    - System connected to AC power
    
    Note:
    Minimums are the baseline for what is necessary to install Solus.
    Recommendations are intended as a guide for a better experience.
    Your requirements may differ depending on your intended system use.
    
|                       | Minimum                         | Recommended                                                                               |
| --------------------- | ------------------------------- | ----------------------------------------------------------------------------------------- |
| Disk space free       | 10GB / 9.3GiB                   | 25GB / 23.3GiB                                                                            |
| Memory (RAM)          | 4GB                             | 8GB or more                                                                               |
| Processor (CPU)       | 64-bit (x86_64) processor       | [x86-64-v2](https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels) 2GHz quad core |
| System firmware       | BIOS / UEFI                     | UEFI                                                                                      |
| Display Adapter (GPU) | Any onboard / dedicated adapter |                                                                                           |

    
    Note:
    Desktop environments that are more feature rich use the graphics card for 3D-acceleration, when possible. They will benefit from more powerful GPUs. Older graphics cards may not support acceleration.
```

**Comment by ermo** [comment]
I like this proposal.

**Comment by davidjharder** [comment]
Because of the heinous way the main site was built, fiddling with the "system requirements" content on the Downloads page requires writing raw HTML: https://github.com/getsolus/solus-site.github.io/blob/main/themes/solus/layouts/shortcodes/pages/download.html

More irritating: There is no way to link directly to "system requirements" on the main site. A link from, say, the help center would dump users looking for system requirements onto the top of the downloads page, where they can't see anything about system requirements.

My alternate proposal would be to change system requirements on the main site to a link pointing to the help center, where we have the nice table.

**Comment by TraceyC77** [comment]
Good points. I like the idea of centralizing the system requirements in the help center, and linking to it from the appropriate places (main page included)

**Comment by davidjharder** [comment]
This is resolved
