### ISSUE TITLE
RFC: Remove "Building Android on Solus" page

### ISSUE THREAD

**Issue by davidjharder** [getsolus/help-center-docs#508]
This page https://help.getsol.us/docs/user/software/development/android is outdated as evidenced by this 3 year old issue https://github.com/getsolus/help-center-docs/issues/278

I propose we remove this page from the help center. It's quite niche, and android developers should have enough knowledge to "translate" the official docs into Solus.

**Comment by Staudey** [comment]
Agreed. If no one cares enough to keep this page up-to-date and relevant it's of little use (and potentially confusing for users)

**Comment by TraceyC77** [comment]
Agreed.

**Comment by sheepman4267** [comment]
Agreed. The only solus-specific thing that I see there is installing dependencies, and that's just... not hard to do.
