### ISSUE TITLE
Document sourceforge source policy

### ISSUE THREAD

**Issue by malfisya** [getsolus/help-center-docs#534]
From @ReillyBrogan via matrix

Packagers and reviewers of package PRs, the following is the only acceptable format for SourceForge downloads URLs:
```
https://sourceforge.net/projects/hplip/files/hplip/3.23.12/hplip-3.23.12.tar.gz
```
- Note that the URL begins with `https://sourceforge.net/`, and does not point to a mirror. Solbuild has been improved in recent months and redirects correctly as needed for SourceForge downloads.
- Note also that the path starts with `/project/$project_name/`
- There is no trailing` /download` after the filename. This is important, if you do not do this then solbuild might reuse a previous version if you build without changing the checksum. If there is a trailing `/download` then solbuild will download the file as download in the source folder as `$checksum/download`. Solbuild checks to see if there is already a file in the `$checksum` folder with the expected output name and if present will reuse it, which would be very bad here.

**Comment by davidjharder** [comment]
ref: https://github.com/getsolus/packages/commit/7f21bc38cfb0aa99d41225828171bf7a5d5df4ce
