### ISSUE TITLE
Null RSS entries in `monitoring.yml`

### ISSUE THREAD

**Issue by davidjharder** [getsolus/help-center-docs#582]
As discussed in the Packaging Matrix Room:

* When no rss feed is available for a given package, the rss line should look like `rss: ~`
* NOT `rss: null` (This is a remnant of the blank template)
* This line in the docs is now wrong: *You must, at minimum, fill out id and check if the package has a [CPE name](https://help.getsol.us/docs/packaging/monitoring.yml/#what-is-a-cpe-name). rss should be deleted if no feed is available.*

**Comment by Staudey** [comment]
`null` and `~` should be equivalent in YAML, AFAIK

**Comment by davidjharder** [comment]
My thinking is we prefer ~ to demonstrate that someone has checked, and not forgotten to change the template

**Comment by davidjharder** [comment]
We could, of course, just change the template

**Comment by Staudey** [comment]
I can do that. Would save some manual editing, but you lose the benefit of recognizing who has checked the value. Tough I guess the act of removing the comments can take its place for that purpose.
(gonna add comments to the comments making clear that they should not be included)
