### ISSUE TITLE
Update packaging changes page

### ISSUE THREAD

**Issue by malfisya** [getsolus/help-center-docs#585]
This page https://help.getsol.us/docs/packaging/packaging-changes has not been updated since May '24. There are a few changes happened until recently. This issue is to track what has changed and when did it changed.

- `monitoring.yml` is now strongly suggested and there is a warning in CI
- AppStream metainfo is now required for all desktop packages
- `ent` is now part of starter requirement
- Document new `taskfile.yml` commands
- add more here

**Comment by Staudey** [comment]
- Whitelist requirement for static libs
- Mandatory `rss` field for monitoring.yml

I'll take a closer look when I'm not in my phone

**Comment by davidjharder** [comment]
@malfisya Is there anything else you can think of that we missed?

**Comment by malfisya** [comment]
Will add more:
- Checkbox added in PR template for Sync notes

**Comment by Staudey** [comment]
I left that one out on purpose because you see it anyway when you submit a PR (and, mainly, because I couldn't figure out a way to phrase it that didn't sound dumb)

**Comment by Staudey** [comment]
Wait, actually I did add it, even though it sounds dumb
